default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: localflix
  password:

development:
  <<: *default
  database: localflix-development

test:
  <<: *default
  database: localflix-test
