# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01f2eae7fa670b26bdc4e5c6b9535a206f2b7e5e95352a0a1cd56941b579457375235add8ad88eb26e8e2374b21a3a22e09d3c6cb43d710df4c48efa519c5c68
  tv_show_dir: '~/Downloads/TV/'

test:
  secret_key_base: bcdb1d0ba0fa51a0254f68428b464a535139ea41e59fedf6aae2889d327c7a2dacd702da5a34c935faebf1d6a5f188e67932d8f7e53f90df701862a27c56bd0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
